### ISSUE TITLE
Stacktrace is not readable after source map upload

### ISSUE THREAD

**Issue by nzkn** [getsentry/sentry-dart-plugin#104]
### Environment

Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (5 weeks ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1

I am also using this version of the package:
sentry_dart_plugin: 1.1.0

### Steps to Reproduce

I am trying to upload source maps to sentry to make the stack trace of errors captured on the web readable.

1. Added sentry_dart_plugin dependency and sentry config into the pubspec.yaml:
```
sentry_dart_plugin: 1.1.0

sentry:
  log_level: debug
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  url: "some-url"
  project: "some-project"
  org: "some-org"
  auth_token: "some-token"
  commits: auto
```

2. Built flutter web project:
`fvm flutter build web --dart-define=ENVIRONMENT=local --source-maps`

3. Run the upload command (executes successfully):
`fvm flutter packages pub run sentry_dart_plugin`

4. Run the web app and throw some exception in the code.

### Expected Result

I expect stacktrace of the exception to be readable.

### Actual Result

Stacktrace is not readable. 
<img width="716" alt="Screenshot 2023-04-14 at 17 55 16" src="https://user-images.githubusercontent.com/69199372/232079327-30d274e1-1cc6-47b7-b9d0-79eb4d65893c.png">

I also tried to upload the source map as explained in this stackloverflow thread (https://stackoverflow.com/a/66032169/11358566). The upload is successful but the stacktrace remains not readable. I can see uploaded source maps in the project settings, so I am not sure if that's some issue with sentry or if I am doing anything wrong.
