### ISSUE TITLE
Support custom `dist`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart-plugin#132]
https://github.com/getsentry/sentry-dart-plugin/blob/5b758325506d3ed7be2ad9ad887e0df741518e42/lib/sentry_dart_plugin.dart#L210

so you can do it in the pubspec

```yaml
sentry:
  release: ...
  dist: ...
```
