### ISSUE TITLE
Incorrect source maps for Flutter web

### ISSUE THREAD

**Issue by Snahi** [getsentry/sentry-dart-plugin#142]
### Environment

sentry_dart_plugin: 1.5.0
Flutter: 3.10.3

### Steps to Reproduce

1. Create Flutter app:
```
void main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn = 'put your dsn here';
      options.tracesSampleRate = 1.0;
    },
    appRunner: () {
      WidgetsFlutterBinding.ensureInitialized();
      runApp(const MyApp());
    },
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sentry Test',
      home: Scaffold(
        body: Center(
          child: TextButton(
            onPressed: () => throw Exception('Exception from release to test Sentry'),
            child: const Text('Throw Exception'),
          ),
        ),
      ),
    );
  }
}
```

2. Add this configuration to `pubspec.yaml`
```
sentry:
  upload_source_maps: true
  upload_sources: true
  project: <your project name>
  org: <your organization name>
  url: <your url>
  wait_for_processing: true
  ignore_missing: false
  ```

3. Set env variable `SENTRY_AUTH_TOKEN`
4. Create git repository and commit your changes
5. run: `flutter build web --source-maps`
6. run: `dart pub global activate sentry_dart_plugin`
7. run: `dart pub global run sentry_dart_plugin`
8. run: `flutter run --release`
9. Tap the "Throw Exception" button

### Expected Result
The exception shows in issues with the correctly decoded stack trace

### Actual Result
The issue name is "minified:GO". Stack trace is not decoded properly:

![Screenshot 2023-07-27 at 12 15 38](https://github.com/getsentry/sentry-dart-plugin/assets/37747394/1ccd96cd-a657-4168-8ea2-153da352c0a2)
