### ISSUE TITLE
Plugin does not upload Flutter native symbols

### ISSUE THREAD

**Issue by r-i-c-o** [getsentry/sentry-dart-plugin#148]
For some reason, Sentry does not display Flutter native calls despite all symbols were uploaded via `sentry-dart-plugin`

### Environment

Flutter 3.10.6
sentry_dart_plugin: ^1.5.0
pubspec content:
```
sentry:
  upload_debug_symbols: true
  project: our-project-name
  org: project-org
  auth_token: our-token
  wait_for_processing: true
  log_level: warn
  commits: false
```

### Steps to Reproduce

1. run `flutter build ios`
2. run `dart run sentry_dart_plugin`

### Expected Result

No `<redacted>` messages in Sentry

### Actual Result

![изображение](https://github.com/getsentry/sentry-dart-plugin/assets/54285735/6b5de33f-db32-4ef7-b7c8-7d33633c5cc7)
