### ISSUE TITLE
Support to obfuscation-map

### ISSUE THREAD

**Issue by GuilhermeVendramini** [getsentry/sentry-dart-plugin#154]
Hi,
I'm building my app with obfuscate:

flutter build apk --release --flavor prod --obfuscate --split-debug-info=debug_info --extra-gen-snapshot-options=--save-obfuscation-map=debug_info/map-obfuscation.json

And here is my pubspec.yaml

```yml
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  log_level: warn # possible values: trace, debug, info, warn, error
  project: my-project
  org: my-org
  auth_token: my-token
```

So, after run `flutter packages pub run sentry_dart_plugin` I go to my project issues and they title aren't  [human readable](https://docs.flutter.dev/deployment/obfuscate#read-an-obfuscated-name).

I don't know if I'm missing something or if Sentry doesn't support obfuscated title decoding.

<img width="475" alt="Captura de Tela 2023-09-05 às 22 11 27" src="https://github.com/getsentry/sentry-dart-plugin/assets/3814765/b0c66317-710f-406e-b3b6-67ec51a73eb6">
