### ISSUE TITLE
Android stacktraces are not readable

### ISSUE THREAD

**Issue by 1mavic** [getsentry/sentry-dart-plugin#158]
Hello!
I am having issue with sentry_dart_plugin.
Unable to read stack trace for android. With IOS everything works fine.

<img width="845" alt="Снимок экрана 2023-09-18 в 14 18 44" src="https://github.com/getsentry/sentry-dart-plugin/assets/11533738/d0df7e6c-126a-4510-a6a7-f96c06ebf3e3">
<img width="827" alt="Снимок экрана 2023-09-18 в 14 20 21" src="https://github.com/getsentry/sentry-dart-plugin/assets/11533738/68d42e3a-69de-4f6d-8d21-a3d7fb8738dd">

sentry_dart_plugin version 1.5.0

Flutter doctor:
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.2 22G91 darwin-arm64, locale ru-EE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources

Build release with --obfuscate --split-debug-info=path

android/app/build.gradle
```
apply plugin: 'io.sentry.android.gradle'
```
```
 buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
```

```
sentry {
    uploadNativeSymbols = false
    includeNativeSources = true
    experimentalGuardsquareSupport = true
    autoUploadProguardMapping = true
}
```

android/build.gradle
```
classpath 'io.sentry:sentry-android-gradle-plugin:3.12.0'
```

android/gradle.properties
```
android.bundle.enableUncompressedNativeLibs=false
```

proguard-rules.pro
```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String); 
}
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
```

android/sentry.properties
```
defaults.org={org}
defaults.project={project}
auth.token={token}
```

pubspec.yaml
```
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  project:{project}
  org: {org}
  auth_token: {token}
  url: {sentry-url}
  wait_for_processing: true
  log_level: error # possible values: trace, debug, info, warn, error
  commits: auto
  ignore_missing: true
```

In settings-project-Debug Information Files - files uploaded
As proGuard mappings uploaded too.

log:
```

> Prepared debug information files for upload

> Uploaded 3 missing debug information files

> File processing complete:

       OK 8d2c1676-3430-9794-d841-697d9a1e8dae (app.so; arm library)
       OK 03909b34-7949-b795-af40-333ab4ac07ea (app.so; arm64 library)
       OK fecfc475-fb24-f2f6-1865-6ce0b5e8e3db (app.so; x86_64 library)
```
