### ISSUE TITLE
Is sentry configuration possible with a separate yaml file instead of pubspec.yaml

### ISSUE THREAD

**Issue by memishood** [getsentry/sentry-dart-plugin#194]
I want to move the following configuration to a separate yaml file (eg: `sentry.yaml`) to make pubspec yaml file more clear. I checked the documentation but I couldn't it.

```yaml
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: false
  ...
```
