### ISSUE TITLE
prefix and urlPrefix do not add prefix to uploaded source map

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-dart-plugin#321]
Add the sentry dart plugin to an app:

```
dependencies:
  sentry_dart_plugin: ^2.4.1
  sentry_flutter: ^8.14.2

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  urlPrefix: ~/urlprefixpath/ 
  # (same behaviour when using   prefix: ~/urlprefixpath/)
  project: flutter
  org: dev-curumas
  commits: false
```

Build the app for web:
```
flutter build web --base-href=/urlprefixpath/ --source-maps
```

Run the plugin to upload files to Sentry:
```
 dart run sentry_dart_plugin 
```

The source maps are uploaded but the prefix is not added: 

<img width="418" alt="Image" src="https://github.com/user-attachments/assets/d6077e79-b15e-4fe9-8b49-4e01b32f17e5" />

The debug logs from the CLI do not show the prefix being used:
```
sentry-cli was invoked with the following command line: "testApps/flutter/leapp/.dart_tool/pub/bin/sentry_dart_plugin/sentry-cli" "--auth-token" "[REDACTED]" "releases" "--org" "dev-curumas" "--project" "flutter" "files" "leapp@2.0.0+3" "upload-sourcemaps" "build/web" "--ext" "map" "--ext" "js" "--dist" "3"

or

sentry-cli was invoked with the following command line: "testApps/flutter/leapp/.dart_tool/pub/bin/sentry_dart_plugin/sentry-cli" "--auth-token" "[REDACTED]" "releases" "--org" "dev-curumas" "--project" "flutter" "files" "leapp@2.0.0+2" "upload-sourcemaps" "build/web" "--ext" "map" "--ext" "js" "--dist" "2"
```
