### ISSUE TITLE
Getting some cryptic messages on Sentry

### ISSUE THREAD

**Issue by aggeloskoutanis** [getsentry/sentry-dart-plugin#324]
### Environment

Flutter 3.24

### Steps to Reproduce

1. Pubspec config 

```
sentry:
  project: [censored]
  org: [censored]
  upload_debug_symbols: true
  upload_source_context: true
  wait_for_processing: true
  ignore_missing: true
```

2. Codemagic
I built using Shorebird with 

`-- --obfuscate --split-debug-info=./build/app/outputs/symbols`

3. In Sentry, I can see in the ProGuard section that the mappings have been successfully uploaded.

### Expected Result

See events that don't have cryptic names. For example, ItemsBloc@LoadItems.

### Actual Result

Looking at an error trace. Instead of seeing BlocName@BlocEvent, I get to see a cryptic message.

Similar cryptic messages appear for UI Click event traces

<img width="863" alt="Image" src="https://github.com/user-attachments/assets/2394bbe7-3afb-4881-b8cf-56641c452a7e" />
