### ISSUE TITLE
Stack traces are not deobfuscasted

### ISSUE THREAD

**Issue by talp-flytrex** [getsentry/sentry-dart-plugin#328]
### Environment

```
dev_dependencies:
  sentry_dart_plugin: ^3.0.0

# See: https://docs.sentry.io/platforms/dart/debug-symbols/dart-plugin/
sentry:
  project: xxx
  org: xxx
  upload_debug_symbols: true
  upload_source_context: true
  symbols_path: symbols/
```

Output of `flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.32.4, on macOS 15.5 24F74 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] VS Code (version 1.101.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

Build commands:
For Android:
```
flutter "build" "appbundle" "--obfuscate" "--split-debug-info=symbols/" "--release"
```

For iOS:
```
$ flutter "build" "ios" "--obfuscate" "--split-debug-info=symbols/" "--release" "--no-codesign"
```

In both cases debug files are uploaded successfully to Sentry.
But the de-obfuscation fails:

Android:
![Image](https://github.com/user-attachments/assets/b5fec6b1-ffb0-42d8-99ee-79bd55e76cc8)

iOS:
![Image](https://github.com/user-attachments/assets/b59e74f4-c37c-4a88-b023-892416c7f74c)
