### ISSUE TITLE
Release version and dist not set by default with pubspec.yaml

### ISSUE THREAD

**Issue by Ortes** [getsentry/sentry-dart-plugin#330]
### Environment

sentry_dart_plugin: ^3.0.0
sentry_flutter: ^9.1.0

### Steps to Reproduce

Execute `dart pub run sentry_dart_plugin` in a flutter project

configuration in pubspec.yaml :

```yaml
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  project: ...
  org: ...
  log_level: info
  commits: true
  ignore_missing: true
  web_build_path: web
```

EDIT:
Is does not works either with release and dist set in pubspec.yaml:

```yaml
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  project: ...
  org: ...
  log_level: info
  commits: true
  release: 2.4.7
  dist: 57
  ignore_missing: true
  web_build_path: web
```

### Expected Result

I want the release version and the dist number to be automatically set with my pubspec.yaml

### Actual Result

I get this message in my dashboard:

"No releases associated with this upload."

<img width="1024" alt="Image" src="https://github.com/user-attachments/assets/aebbc535-9b57-4e7d-abfd-c4e805464314" />
