### ISSUE TITLE
Support sentry.properties

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart-plugin#42]
Right now the configuration is read thru the plugin configuration or via env. var.
Sentry Wizard is able to generate a properties file, the plugin could read the conf. from this file as well.

**Comment by PawlikMichal25** [comment]
Just a small note:
If someone is using `pubspec.yaml` configuration then it's impossible (as far as I know) to read environment variables inside it eg:
```yaml
sentry:
   upload_debug_symbols: true
   project: ${PROJECT_FLAVOR}
   auth_token: ${AUTH_TOKEN}
```
It would be amazing if it were possible with this config file
