### ISSUE TITLE
Sentry Flutter Web

### ISSUE THREAD

**Issue by kenNg1** [getsentry/sentry-dart-plugin#70]
Sentry flutter web currently uploads the source maps e.g. below, and you can see every filename in our repo. Is there any way to prevent this from happening while ensuring errors can be traced in Sentry issues viewer?

Chrome sources tab:

![image](https://user-images.githubusercontent.com/25297786/204002132-32a28920-1f4c-41a4-803e-25622ddf6039.png)

Existing configuration in `pubspec.yaml`

```
sentry:
  upload_native_symbols: true
  upload_source_maps: true
  include_native_sources: true
  project: xxx
  org: xxx
  auth_token:
  wait_for_processing: false
  log_level: error
  commits: false
  web_build_path: build/web
  url: ~
```
