### ISSUE TITLE
Flutter web source maps - file structure and files showing in chrome console

### ISSUE THREAD

**Issue by kenNg1** [getsentry/sentry-dart-plugin#71]
Platform:

 Flutter Web
CanvasKit (Flutter Web) enabled

Not exactly a bug but more of a data sensitivity issue. Sentry flutter web currently uploads the source maps e.g. below, and you can see every filename in our repo. Is there any way to prevent this from happening while ensuring errors can be traced in Sentry issues viewer?

Chrome sources tab:

![image](https://user-images.githubusercontent.com/25297786/204012528-f1266e78-0d5d-44de-8580-f7e10e1c9d3b.png)

Existing config:

```
sentry:
  upload_native_symbols: true
  upload_source_maps: true
  include_native_sources: true
  project: xxx
  org: yyy
  auth_token:
  wait_for_processing: false
  log_level: error
  commits: false
  web_build_path: build/web
  url: ~
```
